### ISSUE TITLE
Error when building locally

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#88] opened 2020-06-03 22:17 UTC
I'm getting an error when building the up locally, everything is fine on vercel though.

```terminal
|> Build error occurred Error: Export encountered errors on following paths
     Error: Network error: Only absolute URLs are supported
```

**Steps to reproduce:**

- yarn build

**Results:**

<img width="993" alt="Screen Shot 2020-06-03 at 3 15 52 PM" src="https://user-images.githubusercontent.com/5281701/83694608-3710e200-a5ad-11ea-8d37-961ff63f4798.png">

**Comment by Vadorequest** [comment] 2020-06-03 22:51
On what branch are you?

Try deleting all node_modules and reinstalling.

**Comment by samuelcastro** [comment] 2020-06-03 23:04
branch:  v2-mst-aptd-gcms-lcz-st

`yarn.lock` and `node_modules`  were removed before.

```terminal
Error occurred prerendering page "/fr/examples/native-features/example-with-ssg". Read more: https://err.sh/next.js/prerender-error
Error: Network error: Only absolute URLs are supported
```

**Comment by Vadorequest** [comment] 2020-06-04 00:25
You must be doing something like fetching an external service using `fetch`?

https://github.com/vercel/next.js/issues/1213

**Comment by samuelcastro** [comment] 2020-06-04 16:21
I'm not doing anything new, this is a clean clone of this repo.

**Comment by Vadorequest** [comment] 2020-06-04 17:11
Weird, it's working on my side on both MacOs and Windows 8 + 10.

I'll try re-pulling that branch and see what happens.

**Comment by Vadorequest** [comment] 2020-06-04 19:02
I tried to do a clean install and it works as expected.

https://youtu.be/E0TUVE1VEEQ

What OS are you using? I'm gonna have a hard time fixing this one without reproduction.

**Comment by samuelcastro** [comment] 2020-06-04 21:54
You didn't follow the steps to reproduce which is just to run: `yarn build`, I also can start the app with `yarn start` without any issues.

Might be related to my `now` version though, not sure.

Using `macOS Mojave`

**Comment by Vadorequest** [comment] 2020-06-04 23:25
Well, it wasn't obvious it was during `yarn build`.

It shouldn't be related to the `now` CLI anymore, but should basically run `next build`.

I've never tried to manually build from my machine to be honest, since the point of this boilerplate is to deploy mainly to Vercel.

I just tried and I get the same error as you do.

**Comment by Vadorequest** [comment] 2020-06-04 23:36
Seems related to:

https://github.com/vercel/next.js/discussions/12732
https://github.com/vercel/next.js/pull/12353#issuecomment-627064091

I strongly believe it comes from the new built-in `fetch` function.

Opened issue: https://github.com/vercel/next.js/issues/13780

**Comment by samuelcastro** [comment] 2020-06-05 00:34
> Well, it wasn't obvious it was during `yarn build`.

Well that was the only step to reproduce I've added in my original comment 😄 , not sure why it wasn't obvious. :/

> Steps to reproduce:
> 
> yarn build

Thanks for opening up the issue, I wanted to make sure it wasn't something in my environment.

**Comment by Vadorequest** [comment] 2020-06-05 09:03
I had missed that section 😅 Tired from working overnight maybe? :D

**Comment by Vadorequest** [comment] 2020-06-05 12:26
Fixed by https://github.com/UnlyEd/next-right-now/commit/1ed2c6a809709636b8322f76234359bf5f7f5a44

See https://github.com/vercel/next.js/issues/13780#issuecomment-639446017

**Closed as completed by Vadorequest** 2020-06-05 12:26 UTC
Labels: bug

**Comment by samuelcastro** [comment] 2020-06-05 16:11
Thank you!
