### ISSUE TITLE
Use Locize locales/languages as single source of truth for the whole application

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#201] opened 2020-11-10 19:19 UTC
It'd be way better to load supported languages automatically rather than rely in hard coded array that always need to be updated whenever a new language is included.

Solution: 

```javascript
import Locize from "i18next-locize-backend";
const locize = new Locize(options);

locize.getLanguages((err, data) => {
  /*
  data is:

  {
    "en": {
      "name": "English",
      "nativeName": "English",
      "isReferenceLanguage": true,
      "translated": {
        "latest": 1
      }
    },
    "de": {
      "name": "German",
      "nativeName": "Deutsch",
      "isReferenceLanguage": false,
      "translated": {
        "latest": 0.9
      }
    }
  }
  */
});

// or
i18next.services.backendConnector.backend.getLanguages(callback);
```

https://github.com/locize/i18next-locize-backend#backendgetlanguages

**Comment by Vadorequest** [comment] 2020-11-10 20:20
What's the "hardcoded array" you mentioned?

**Comment by samuelcastro** [comment] 2020-11-10 20:37
@Vadorequest  https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-gcms-lcz-sty/src/i18nConfig.js#L7

**Comment by Vadorequest** [comment] 2020-11-10 21:05
I don't really understand what you'd like to do instead of the current behaviour.

**Comment by samuelcastro** [comment] 2020-11-10 22:15
Load the array of supported languages directly from locize instead of maintain this array hardcoded in the project.

**Comment by Vadorequest** [comment] 2020-11-10 22:33
Well, feel free to do so in your app then, but it's not what I'd recommend as a default.

The reason behind this choice is that there shouldn't be allowed Locize languages that aren't allowed within the app, and the `supportedLocales` helps ensuring only the languages that are explicitely allowed can be used for i18n.

Does that make sense?

**Comment by samuelcastro** [comment] 2020-11-13 16:47
Ok, I just don't think that's the best approach, having a single source of truth would simplify things.

**Comment by Vadorequest** [comment] 2020-11-13 18:05
Well, I actually consider `supportedLocales` as the single source of truth. 🤔 

What would be the other source of truth?

**Comment by samuelcastro** [comment] 2020-11-13 18:49
If you add the language you need on `supportedLocales` and not on Locize it won't work and vice-versa, so there are 2 different places where this need to be setup which I consider 02 source of truth.

**Comment by Vadorequest** [comment] 2020-11-13 19:00
Okay, I finally understand the underlying issue, it really wasn't clear to me until now.

The issue is that you can define languages your app uses both on Locize and on the project settings using `supportedLocales`. And if they get out of sync then bad things happen. You'd prefer to use `getLanguages` instead of `supportedLocales`, so that the project has only one single source of truth.

This is not a small change, as it has several impacts across the app, and server/browser implications. Also, that'd mean you need to fetch Locize during initial build step when generating static pages and so on. Or similar.

The easiest course of action is to improve the current documentation, and make it obvious `supportedLocales` should always be identical to the Locize configuration.

**Comment by samuelcastro** [comment] 2020-11-13 19:05
Glad you got the message now 😄 

This will be a huge improvement, less work for devs === best development experience === more adoption === more users of NRN.

Thanks.

**Comment by Vadorequest** [comment] 2020-11-21 14:05
I'm not sure I ever want to do this, here are my reasons:
- The current way isn't so complicated, one just need to be careful when adding a new language to also add it to `supportedLocales` array
- Using Locize as single source of truth will make the workflow quite a lot more complicated, because we'll need to fetch locize when building the app, from `next.config.js`
- Also, it'll make it harder to adapt the source code, for people who aren't using Locize

Overall, the cons outweigh the gains, IMHO.

**Comment by samuelcastro** [comment] 2020-11-23 17:06
For people that are not using Locize I think the best approach would be create a different preset without it.

I don't think it's going to be a lot more complicated, but anyway it's your call, whatever you decide. I'll implement it in my project anyway at some point in the future.

Feel free to close this if you want.

**Comment by Vadorequest** [comment] 2021-01-09 08:12
Closing, documentation will be updated in https://github.com/UnlyEd/next-right-now/pull/238

**Closed as completed by Vadorequest** 2021-01-09 08:12 UTC
Labels: documentation, enhancement, help wanted
