### ISSUE TITLE
Warning on Vercel build

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/next-right-now#143] opened 2020-07-29 18:55 UTC
I'm getting this warning when building up on vercel:

```
WARNING: your application is being opted out of @vercel/next's optimized lambdas mode due to legacy routes in now.json. http://err.sh/vercel/vercel/next-legacy-routes-optimized-lambdas
```

**Comment by Vadorequest** [comment] 2020-07-29 19:01
Duplicate of https://github.com/UnlyEd/next-right-now/issues/130

**Closed as completed by Vadorequest** 2020-07-29 19:01 UTC
