### ISSUE TITLE
i18nRedirect - wrong logic on dynamic routes with both params - normal & query

### ISSUE THREAD

**Issue by 7iomka** [UnlyEd/next-right-now#144] opened 2020-07-29 20:06 UTC
If I have `site.com/en/catalog/5?brand=2`page if I use i18nRedirect to `fr` language
instead of `site.com/fr/catalog/5?brand=2`
i go to `site.com/fr/catalog/[id]?brand=1&id=6`

Dynamic url structure for this page is `[locale]/catalog/[id]` with query parameter brand passed with Link;

**Comment by 7iomka** [comment] 2020-07-29 20:08
My current workaround (it's a bit hard)
```ts
const { query } = router;
  let newAsPath = router.pathname.replace('[locale]', locale);
  const { locale: localeParam, ...allParamsExceptLocale } = query;
  const realQueryParams = {};

  // eslint-disable-next-line array-callback-return
  Object.keys(allParamsExceptLocale).map((param) => {
    const paramValue = Array.isArray(allParamsExceptLocale[param])
      ? (allParamsExceptLocale[param] as Array<string>).join(',')
      : (allParamsExceptLocale[param] as string);
    if (router.pathname.includes(`[${param}]`)) {
      newAsPath = newAsPath.replace(`[${param}]`, paramValue);
      return;
    }
    realQueryParams[param] = paramValue;
  });

  const queryParamsString: string = !isEmpty(realQueryParams) ? `?${new URLSearchParams(realQueryParams)}` : '';

  const newUrl = newAsPath + queryParamsString;

  if (forcePageReload) {
    window.location.href = newUrl;
  } else {
    router.push(router.pathname, newUrl);
  }
```

**Comment by Vadorequest** [comment] 2020-07-29 20:26
It may be related to https://github.com/UnlyEd/next-right-now/issues/142, I noticed this issue today.

There was a recent PR about I18nLink at https://github.com/UnlyEd/next-right-now/pull/136, I believe something may have gone wrong then. I'll try to fix it ASAP.

**Comment by samuelcastro** [comment] 2020-08-21 18:08
Any updates on this?

**Comment by Vadorequest** [comment] 2020-08-24 09:56
I was off those past 2 weeks and just got back today. This is still the most prioritized issue on NRN and I'll try to tackle it this week.

**Comment by Vadorequest** [comment] 2020-08-25 17:43
I actually misunderstood this bug and thought it was something else. It's not as critical as I first thought of.

I added unit tests for the I18nLink component: https://github.com/UnlyEd/next-right-now/pull/148 it's not yet merged.

@7iomka Could you post your code? Did you use `params` and `query` correctly? Because my tests are working fine.

```ts
    test('when using route params and query route params using nested paths', () => {
      const renderer = TestRenderer.create(<I18nLinkTest href={'/products/favourites/[id]'} params={{id: 5}} query={{userId: 1}} />);
      const link: any = renderer.toJSON();
      console.log(link)

      expect(link.type).toEqual('a');
      expect(link.children).toEqual(['Text']);
      expect(link.props.href).toEqual('/en/products/favourites/5?userId=1');
      expect(link).toMatchSnapshot();
    });

    test('when using route params and query route params using nested paths and forcing locale', () => {
      const renderer = TestRenderer.create(<I18nLinkTest href={'/products/favourites/[id]'} params={{id: 5}} query={{userId: 1}} locale={'fr'} />);
      const link: any = renderer.toJSON();
      console.log(link)

      expect(link.type).toEqual('a');
      expect(link.children).toEqual(['Text']);
      expect(link.props.href).toEqual('/fr/products/favourites/5?userId=1');
      expect(link).toMatchSnapshot();
    });
```

**Comment by Vadorequest** [comment] 2020-08-25 18:43
@samuelcastro Where you also affected by this, or just checking up?

**Comment by 7iomka** [comment] 2020-08-27 15:26
@Vadorequest 
Hi. I just called redirect when **dynamic page**, that use query params is opened
![image](https://user-images.githubusercontent.com/18473137/91462301-b6ebd700-e892-11ea-8f8f-62b5b8ee4f14.png)

DEMO: https://www.youtube.com/watch?v=RITgtOkh76c

My final workaround that fixes:
```ts
export const i18nRedirect = (locale, router: NextRouter, forcePageReload = false): void => {
  const { query } = router;
  let newAsPath = router.pathname.replace('[locale]', locale);
  const { locale: localeParam, ...allParamsExceptLocale } = query;
  const realQueryParams = {};

  // eslint-disable-next-line array-callback-return
  Object.keys(allParamsExceptLocale).map((param) => {
    const paramValue = Array.isArray(allParamsExceptLocale[param])
      ? (allParamsExceptLocale[param] as Array<string>).join(',')
      : (allParamsExceptLocale[param] as string);
    if (router.pathname.includes(`[${param}]`)) {
      newAsPath = newAsPath.replace(`[${param}]`, paramValue);
      return;
    }
    realQueryParams[param] = paramValue;
  });

  const queryParamsString: string = !isEmpty(realQueryParams) ? `?${new URLSearchParams(realQueryParams)}` : '';

  const newUrl = newAsPath + queryParamsString;

  if (forcePageReload) {
    window.location.href = newUrl;
  } else {
    router.push(router.pathname, newUrl);
  }
};
```

**Comment by samuelcastro** [comment] 2020-08-27 18:20
I'm just checking up, I haven't faced this problem yet.

**Comment by Vadorequest** [comment] 2020-09-02 06:46
@7iomka Thanks for the demo. I understand the issue, but I'm not experiencing it myself. 🤔 

Could you share the code that performs the language changes? As it's where the issue is coming from. 

Nevertheless, I'm glad you worked it out. I'll try your change and see how it can be integrated by default.

**Comment by Vadorequest** [comment] 2020-10-09 04:42
Closing this, I believe it's a misusage and not a bug from NRN.

An additional test case has been added to make sure this works as expected:
https://github.com/UnlyEd/next-right-now/commit/d31b346acc736516e7506a28c65d1a1719f807f5

**Closed as completed by Vadorequest** 2020-10-09 04:42 UTC
Labels: bug

**Comment by samuelcastro** [comment] 2021-03-23 17:37
I think this is related: https://github.com/UnlyEd/next-right-now/issues/301
